class Constants:
    REGRESSOR_EPOCH = 200
    REGRESSOR_SAVED_MODEL_PATH = "./Model/Regressor/Regressor.pth"
    REGRESSOR_LOSS_PLOT_PATH = "Plots/Regressor/Regressor_Loss_plot.jpeg"
    REGRESSOR_LR = 0.0001
    REGRESSOR_WEIGHT_DECAY = 1e-5
    REGRESSOR_IN_CHANNEL = 1
    REGRESSOR_HIDDEN_CHANNEL = 3
    REGRESSOR_OUT_DIMS = 2
    REGRESSOR_BATCH_SIZE_CPU = 32
    REGRESSOR_BATCH_SIZE_CUDA = 256

    COLORIZER_EPOCH = 500
    COLORIZER_SAVED_MODEL_PATH = "./Model/Colorizer/Colorizer_100.pth"
    COLORIZER_LOSS_PLOT_PATH = "Plots/Colorizer/Colorizer_Loss_plot.jpeg"
    COLORIZER_LR = 0.0001
    COLORIZER_WEIGHT_DECAY = 1e-5
    COLORIZER_IN_CHANNEL = 3
    COLORIZER_HIDDEN_CHANNEL = 3
    COLORIZER_OUT_DIMS = 2
    COLORIZER_BATCH_SIZE_CPU = 32
    COLORIZER_BATCH_SIZE_CUDA = 256
